##======================================================================================================================
##  TTS - Tiny Test System
##  Copyright : TTS Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: TTS Standalone Generation
on:
  push:
    branches:
      - main

jobs:
  package-standalone:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container:
      image: ghcr.io/jfalcou/compilers:v10
    strategy:
      fail-fast: false
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1

      - name: Configure TTS
        run: |
          git config --global --add safe.directory /__w/tts/tts
          mkdir build && cd build
          cmake .. -G Ninja -DTTS_BUILD_TEST=OFF -DTTS_BUILD_DOCUMENTATION=OFF

      - name: Generate standalone TTS header
        run: |
          cd build && ninja tts-standalone

      - name: Update standalone branch
        run: |
          git fetch origin
          git config --global user.email "tts@nowhere.com"
          git config --global user.name "TTS Standalone Generator"
          git checkout standalone
          cp build/tts.hpp tts.hpp
          git add tts.hpp
          git commit --allow-empty -m "Latest TTS standalone"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "standalone"
